row('http://dbpedia.org/resource/Abelson_murine_leukemia_virus').
row('http://dbpedia.org/resource/Abomasitis').
row('http://dbpedia.org/resource/Actinobacillosis').
row('http://dbpedia.org/resource/Actinobacillus_suis').
row('http://dbpedia.org/resource/Actinomycosis_in_animals').
row('http://dbpedia.org/resource/Addison\'s_disease_in_canines').
row('http://dbpedia.org/resource/Aerococcus_viridens_var._homari').
row('http://dbpedia.org/resource/Aeromonas_hydrophila').
row('http://dbpedia.org/resource/Aeromonas_salmonicida').
row('http://dbpedia.org/resource/African_horse_sickness').
row('http://dbpedia.org/resource/African_swine_fever_virus').
row('http://dbpedia.org/resource/Akabane_virus').
row('http://dbpedia.org/resource/Alcelaphine_herpesvirus_2').
row('http://dbpedia.org/resource/Aleutian_Disease').
row('http://dbpedia.org/resource/Allograft_diseases').
row('http://dbpedia.org/resource/Alopecia_in_animals').
row('http://dbpedia.org/resource/Amantadine').
row('http://dbpedia.org/resource/Ammonia_poisoning').
row('http://dbpedia.org/resource/Amoebic_gill_disease').
row('http://dbpedia.org/resource/Anal_sac_adenocarcinoma').
row('http://dbpedia.org/resource/Anaplasmosis').
row('http://dbpedia.org/resource/Angel_wing').
row('http://dbpedia.org/resource/Animal_trypanosomiasis').
row('http://dbpedia.org/resource/Anisakiasis').
row('http://dbpedia.org/resource/Annual_ryegrass_toxicity').
row('http://dbpedia.org/resource/Anoplocephala_perfoliata').
row('http://dbpedia.org/resource/Anthrax').
row('http://dbpedia.org/resource/Anthrax_mite').
row('http://dbpedia.org/resource/Anthroponotic_disease').
row('http://dbpedia.org/resource/Anticor').
row('http://dbpedia.org/resource/Aphanomyces_astaci').
row('http://dbpedia.org/resource/Arbidol').
row('http://dbpedia.org/resource/Asama_virus').
row('http://dbpedia.org/resource/Ascaridia_galli').
row('http://dbpedia.org/resource/Ascaridiidae').
row('http://dbpedia.org/resource/Ascaris_suum').
row('http://dbpedia.org/resource/Aspergillosis').
row('http://dbpedia.org/resource/Asteroid_hyalosis').
row('http://dbpedia.org/resource/Australian_bat_lyssavirus').
row('http://dbpedia.org/resource/Autosomal_dominant_polycystic_kidney').
row('http://dbpedia.org/resource/Avian_Bornavirus').
row('http://dbpedia.org/resource/Avian_adenovirus').
row('http://dbpedia.org/resource/Avian_botulism').
row('http://dbpedia.org/resource/Avian_encephalomyelitis_virus').
row('http://dbpedia.org/resource/Avian_infectious_bronchitis').
row('http://dbpedia.org/resource/Avian_infectious_bronchitis_virus').
row('http://dbpedia.org/resource/Avian_influenza').
row('http://dbpedia.org/resource/Avian_influenza_in_cats').
row('http://dbpedia.org/resource/Avian_malaria').
row('http://dbpedia.org/resource/Avian_paramyxovirus').
row('http://dbpedia.org/resource/Avian_pneumovirus').
row('http://dbpedia.org/resource/Avian_reovirus').
row('http://dbpedia.org/resource/Avian_sarcoma_leukosis_virus').
row('http://dbpedia.org/resource/Avian_vacuolar_myelinopathy').
row('http://dbpedia.org/resource/Avian_veterinarian').
row('http://dbpedia.org/resource/Avipoxvirus').
row('http://dbpedia.org/resource/Babesia_divergens').
row('http://dbpedia.org/resource/Babesiosis').
row('http://dbpedia.org/resource/Bacterial_cold_water_disease').
row('http://dbpedia.org/resource/Bacterial_kidney_disease').
row('http://dbpedia.org/resource/Bafinivirus').
row('http://dbpedia.org/resource/Balanoposthitis').
row('http://dbpedia.org/resource/Balantidium_coli').
row('http://dbpedia.org/resource/Bald_sea_urchin_disease').
row('http://dbpedia.org/resource/Bas-Congo_virus').
row('http://dbpedia.org/resource/Bath_treatment_(fishkeeping)').
row('http://dbpedia.org/resource/Baylisascaris').
row('http://dbpedia.org/resource/Bennettinia').
row('http://dbpedia.org/resource/Berserk_llama_syndrome').
row('http://dbpedia.org/resource/Besnoitiosis').
row('http://dbpedia.org/resource/Betanodavirus').
row('http://dbpedia.org/resource/Bilious_vomiting_syndrome').
row('http://dbpedia.org/resource/Bird_louse').
row('http://dbpedia.org/resource/Black_Creek_Canal_virus').
row('http://dbpedia.org/resource/Black_band_disease').
row('http://dbpedia.org/resource/Blackhead_disease').
row('http://dbpedia.org/resource/Blackleg_(disease)').
row('http://dbpedia.org/resource/Bladder_cancer_in_cats_and_dogs').
row('http://dbpedia.org/resource/Bladder_stone_(animal)').
row('http://dbpedia.org/resource/Blain_(animal_disease)').
row('http://dbpedia.org/resource/Bloodland_Lake_virus').
row('http://dbpedia.org/resource/Blue_Eye_Disease').
row('http://dbpedia.org/resource/Blue_River_virus').
row('http://dbpedia.org/resource/Bluetongue_disease').
row('http://dbpedia.org/resource/Bokeloh_Bat_lyssavirus').
row('http://dbpedia.org/resource/Bone_cancer_in_cats_and_dogs').
row('http://dbpedia.org/resource/Bordetella_bronchiseptica').
row('http://dbpedia.org/resource/Bordetella_holmesii').
row('http://dbpedia.org/resource/Borna_disease').
row('http://dbpedia.org/resource/Borrelia_anserina').
row('http://dbpedia.org/resource/Botulism').
row('http://dbpedia.org/resource/Bovicola_bovis').
row('http://dbpedia.org/resource/Bovine_Campylobacteriosis').
row('http://dbpedia.org/resource/Bovine_adenovirus').
row('http://dbpedia.org/resource/Bovine_coronavirus').
row('http://dbpedia.org/resource/Bovine_enterovirus').
row('http://dbpedia.org/resource/Bovine_ephemeral_fever').
row('http://dbpedia.org/resource/Bovine_herpesvirus_1').
row('http://dbpedia.org/resource/Bovine_herpesvirus_2').
row('http://dbpedia.org/resource/Bovine_herpesvirus_4').
row('http://dbpedia.org/resource/Bovine_herpesvirus_5').
row('http://dbpedia.org/resource/Bovine_leukemia_virus').
row('http://dbpedia.org/resource/Bovine_malignant_catarrhal_fever').
row('http://dbpedia.org/resource/Bovine_papillomavirus').
row('http://dbpedia.org/resource/Bovine_papular_stomatitis').
row('http://dbpedia.org/resource/Bovine_parvovirus').
row('http://dbpedia.org/resource/Bovine_spongiform_encephalopathy').
row('http://dbpedia.org/resource/Bovine_virus_diarrhea').
row('http://dbpedia.org/resource/Boxer_cardiomyopathy').
row('http://dbpedia.org/resource/Brachycephalic_syndrome').
row('http://dbpedia.org/resource/Brachyspira_pilosicoli').
row('http://dbpedia.org/resource/Braxy').
row('http://dbpedia.org/resource/Brooklynella_hostilis').
row('http://dbpedia.org/resource/Brucella_canis').
row('http://dbpedia.org/resource/Brucellosis').
row('http://dbpedia.org/resource/Bubonic_plague').
row('http://dbpedia.org/resource/Buffalopox').
row('http://dbpedia.org/resource/Bumblefoot_(infection)').
row('http://dbpedia.org/resource/CVBD').
row('http://dbpedia.org/resource/Camelpox').
row('http://dbpedia.org/resource/Campylobacteriosis').
row('http://dbpedia.org/resource/Canarypox').
row('http://dbpedia.org/resource/Cancer_in_cats').
row('http://dbpedia.org/resource/Cancer_in_dogs').
row('http://dbpedia.org/resource/Cancricepon_elegans').
row('http://dbpedia.org/resource/Canine_Chiari-like_malformation').
row('http://dbpedia.org/resource/Canine_Epileptoid_Cramping_Syndrome').
row('http://dbpedia.org/resource/Canine_brain_tumors').
row('http://dbpedia.org/resource/Canine_cognitive_dysfunction').
row('http://dbpedia.org/resource/Canine_degenerative_myelopathy').
row('http://dbpedia.org/resource/Canine_discoid_lupus_erythematosus').
row('http://dbpedia.org/resource/Canine_distemper').
row('http://dbpedia.org/resource/Canine_follicular_dysplasia').
row('http://dbpedia.org/resource/Canine_hepacivirus').
row('http://dbpedia.org/resource/Canine_herpesvirus').
row('http://dbpedia.org/resource/Canine_histiocytic_diseases').
row('http://dbpedia.org/resource/Canine_influenza').
row('http://dbpedia.org/resource/Canine_inherited_demyelinative_neuropathy').
row('http://dbpedia.org/resource/Canine_leishmaniasis').
row('http://dbpedia.org/resource/Canine_pancreatitis').
row('http://dbpedia.org/resource/Canine_parvovirus').
row('http://dbpedia.org/resource/Canine_transmissible_venereal_tumor').
row('http://dbpedia.org/resource/Capillaria_hepatica').
row('http://dbpedia.org/resource/Capnocytophaga_canimorsus').
row('http://dbpedia.org/resource/Caprine_arthritis_encephalitis').
row('http://dbpedia.org/resource/Carnivorous_protist').
row('http://dbpedia.org/resource/Carnus_hemapterus').
row('http://dbpedia.org/resource/Caseous_lymphadenitis').
row('http://dbpedia.org/resource/Cat_flu').
row('http://dbpedia.org/resource/Cat_scratch_disease').
row('http://dbpedia.org/resource/Cat_skin_disorders').
row('http://dbpedia.org/resource/Ceratomyxa_shasta').
row('http://dbpedia.org/resource/Ceratophyllus_borealis').
row('http://dbpedia.org/resource/Cerebellar_abiotrophy').
row('http://dbpedia.org/resource/Cerebellar_hypoplasia_(non-human)').
row('http://dbpedia.org/resource/Chagas_disease').
row('http://dbpedia.org/resource/Chandlerella_quiscali').
row('http://dbpedia.org/resource/Channel_catfish_virus').
row('http://dbpedia.org/resource/Chauliacia_canarisi').
row('http://dbpedia.org/resource/Chauliacia_securigera').
row('http://dbpedia.org/resource/Cherry_eye').
row('http://dbpedia.org/resource/Chicken_anaemia_virus').
row('http://dbpedia.org/resource/Chlamydophila_abortus').
row('http://dbpedia.org/resource/Chlamydophila_felis').
row('http://dbpedia.org/resource/Choke_(horse)').
row('http://dbpedia.org/resource/Chronic_progressive_lymphedema').
row('http://dbpedia.org/resource/Chronic_superficial_keratitis').
row('http://dbpedia.org/resource/Chronic_wasting_disease').
row('http://dbpedia.org/resource/Chrysosporium').
row('http://dbpedia.org/resource/Chytridiomycosis').
row('http://dbpedia.org/resource/Classical_swine_fever').
row('http://dbpedia.org/resource/Coccidia').
row('http://dbpedia.org/resource/Coccidiosis').
row('http://dbpedia.org/resource/Coenurosis').
row('http://dbpedia.org/resource/Coenurosis_in_humans').
row('http://dbpedia.org/resource/Colitis-X').
row('http://dbpedia.org/resource/Collie_eye_anomaly').
row('http://dbpedia.org/resource/Colorado_tick_fever').
row('http://dbpedia.org/resource/Columbicola_extinctus').
row('http://dbpedia.org/resource/Columnaris').
row('http://dbpedia.org/resource/Companion_Animal_Parasite_Council').
row('http://dbpedia.org/resource/Complex_vertebral_malformation').
row('http://dbpedia.org/resource/Congenital_contractural_arachnodactyly_in_cattle').
row('http://dbpedia.org/resource/Congenital_vertebral_anomaly').
row('http://dbpedia.org/resource/Contagious_bovine_pleuropneumonia').
row('http://dbpedia.org/resource/Contagious_caprine_pleuropneumonia').
row('http://dbpedia.org/resource/Contagious_equine_metritis').
row('http://dbpedia.org/resource/Coonhound_paralysis').
row('http://dbpedia.org/resource/Copper_deficiency').
row('http://dbpedia.org/resource/Corneal_dystrophies_in_dogs').
row('http://dbpedia.org/resource/Corneal_ulcers_in_animals').
row('http://dbpedia.org/resource/Covering_sickness').
row('http://dbpedia.org/resource/Cowpox').
row('http://dbpedia.org/resource/Craniomandibular_osteopathy').
row('http://dbpedia.org/resource/Crataerina').
row('http://dbpedia.org/resource/Crataerina_acutipennis').
row('http://dbpedia.org/resource/Crataerina_melbae').
row('http://dbpedia.org/resource/Crataerina_pacifica').
row('http://dbpedia.org/resource/Crataerina_pallida').
row('http://dbpedia.org/resource/Crayfish_plague').
row('http://dbpedia.org/resource/Cricket_paralysis_virus').
row('http://dbpedia.org/resource/Cross-species_transmission').
row('http://dbpedia.org/resource/Cryptocaryon').
row('http://dbpedia.org/resource/Cryptosporidium').
row('http://dbpedia.org/resource/Cutaneous_Streptococcus_iniae_infection').
row('http://dbpedia.org/resource/Cutaneous_larva_migrans').
row('http://dbpedia.org/resource/Cytauxzoonosis').
row('http://dbpedia.org/resource/Dactylogyrus_vastator').
row('http://dbpedia.org/resource/Dasypsyllus').
row('http://dbpedia.org/resource/Degenerative_suspensory_ligament_desmitis').
row('http://dbpedia.org/resource/Demodex_bovis').
row('http://dbpedia.org/resource/Demodex_injai').
row('http://dbpedia.org/resource/Demodicosis').
row('http://dbpedia.org/resource/Dental_caries_(non-human)').
row('http://dbpedia.org/resource/Dermanyssus_gallinae').
row('http://dbpedia.org/resource/Dermoid_sinus').
row('http://dbpedia.org/resource/Derzsy\'s_disease').
row('http://dbpedia.org/resource/Devil_facial_tumour_disease').
row('http://dbpedia.org/resource/Diabetes_in_cats').
row('http://dbpedia.org/resource/Diabetes_in_dogs').
row('http://dbpedia.org/resource/Dicrocoelium_dendriticum').
row('http://dbpedia.org/resource/Dictyocaulus').
row('http://dbpedia.org/resource/Dirofilaria_immitis').
row('http://dbpedia.org/resource/Dirofilaria_repens').
row('http://dbpedia.org/resource/Disease_in_ornamental_fish').
row('http://dbpedia.org/resource/Diseases_and_parasites_in_cod').
row('http://dbpedia.org/resource/Diseases_and_parasites_in_salmon').
row('http://dbpedia.org/resource/Dislocation_of_hip_in_animals').
row('http://dbpedia.org/resource/Distichia').
row('http://dbpedia.org/resource/Dog_pox').
row('http://dbpedia.org/resource/Dog_skin_disorders').
row('http://dbpedia.org/resource/Downer_(animal)').
row('http://dbpedia.org/resource/Drosophila_endobranchia').
row('http://dbpedia.org/resource/Duck_hepatitis_virus').
row('http://dbpedia.org/resource/Duck_plague').
row('http://dbpedia.org/resource/East_Coast_fever').
row('http://dbpedia.org/resource/Eastern_equine_encephalitis_virus').
row('http://dbpedia.org/resource/Ebola_virus').
row('http://dbpedia.org/resource/Ebola_virus_disease').
row('http://dbpedia.org/resource/Ebolavirus').
row('http://dbpedia.org/resource/Echinococcosis').
row('http://dbpedia.org/resource/Echinococcus_granulosus').
row('http://dbpedia.org/resource/Ectopia_lentis').
row('http://dbpedia.org/resource/Ectromelia_virus').
row('http://dbpedia.org/resource/Ectropion').
row('http://dbpedia.org/resource/Edwardsiella_ictaluri').
row('http://dbpedia.org/resource/Edwardsiella_tarda').
row('http://dbpedia.org/resource/Egg_binding').
row('http://dbpedia.org/resource/Ehrlichia_ruminantium').
row('http://dbpedia.org/resource/Ehrlichiosis_(canine)').
row('http://dbpedia.org/resource/Eimeria').
row('http://dbpedia.org/resource/Elaeophora_poeli').
row('http://dbpedia.org/resource/Elaeophora_sagitta').
row('http://dbpedia.org/resource/Elaeophora_schneideri').
row('http://dbpedia.org/resource/Elbow_dysplasia').
row('http://dbpedia.org/resource/Elephant_endotheliotropic_herpesvirus').
row('http://dbpedia.org/resource/Endometrosis').
row('http://dbpedia.org/resource/Enteric_redmouth_disease').
row('http://dbpedia.org/resource/Enterotoxemia').
row('http://dbpedia.org/resource/Entomophthora_muscae').
row('http://dbpedia.org/resource/Entropion').
row('http://dbpedia.org/resource/Eosinophilic_granuloma').
row('http://dbpedia.org/resource/Epidemic_typhus').
row('http://dbpedia.org/resource/Epilepsy_in_animals').
row('http://dbpedia.org/resource/Epizootic').
row('http://dbpedia.org/resource/Epizootic_Hemorrhagic_Disease').
row('http://dbpedia.org/resource/Epizootic_lymphangitis').
row('http://dbpedia.org/resource/Epizootic_shell_disease').
row('http://dbpedia.org/resource/Epizootic_ulcerative_syndrome').
row('http://dbpedia.org/resource/Equine_Lymphangitis').
row('http://dbpedia.org/resource/Equine_Recurrent_Uveitis').
row('http://dbpedia.org/resource/Equine_Venereal_Disease').
row('http://dbpedia.org/resource/Equine_atypical_myopathy').
row('http://dbpedia.org/resource/Equine_encephalitis').
row('http://dbpedia.org/resource/Equine_exertional_rhabdomyolysis').
row('http://dbpedia.org/resource/Equine_herpesvirus').
row('http://dbpedia.org/resource/Equine_herpesvirus_1').
row('http://dbpedia.org/resource/Equine_herpesvirus_2').
row('http://dbpedia.org/resource/Equine_herpesvirus_3').
row('http://dbpedia.org/resource/Equine_herpesvirus_4').
row('http://dbpedia.org/resource/Equine_herpesvirus_5').
row('http://dbpedia.org/resource/Equine_infectious_anemia').
row('http://dbpedia.org/resource/Equine_influenza').
row('http://dbpedia.org/resource/Equine_metabolic_syndrome').
row('http://dbpedia.org/resource/Equine_multinodular_pulmonary_fibrosis').
row('http://dbpedia.org/resource/Equine_nasal_cysts').
row('http://dbpedia.org/resource/Equine_polysaccharide_storage_myopathy').
row('http://dbpedia.org/resource/Equine_protozoal_myeloencephalitis').
row('http://dbpedia.org/resource/Equine_viral_arteritis').
row('http://dbpedia.org/resource/Erbovirus').
row('http://dbpedia.org/resource/Erysipelas').
row('http://dbpedia.org/resource/Erysipeloid').
row('http://dbpedia.org/resource/Escherichia_coli').
row('http://dbpedia.org/resource/Ethmoid_hematoma').
row('http://dbpedia.org/resource/European_Bat_lyssavirus_2').
row('http://dbpedia.org/resource/European_Community_Reference_Laboratory_for_Fish_Diseases').
row('http://dbpedia.org/resource/Eustathia_cultrifera').
row('http://dbpedia.org/resource/Exercise-induced_pulmonary_hemorrhage').
row('http://dbpedia.org/resource/Exocrine_pancreatic_insufficiency').
row('http://dbpedia.org/resource/Exophthalmos').
row('http://dbpedia.org/resource/External_bacterial_infection_(fish)').
row('http://dbpedia.org/resource/Eye_proptosis').
row('http://dbpedia.org/resource/Facial_eczema').
row('http://dbpedia.org/resource/Falcon_adenovirus_A').
row('http://dbpedia.org/resource/Familial_renal_disease_in_animals').
row('http://dbpedia.org/resource/Fasciola_gigantica').
row('http://dbpedia.org/resource/Fasciola_hepatica').
row('http://dbpedia.org/resource/Fascioloides_magna').
row('http://dbpedia.org/resource/Fasciolosis').
row('http://dbpedia.org/resource/Fatty_liver_hemorrhagic_syndrome').
row('http://dbpedia.org/resource/Feather-plucking').
row('http://dbpedia.org/resource/Feather_hole').
row('http://dbpedia.org/resource/Feather_mite').
row('http://dbpedia.org/resource/Feline_Cutaneous_Asthenia').
row('http://dbpedia.org/resource/Feline_acne').
row('http://dbpedia.org/resource/Feline_asthma').
row('http://dbpedia.org/resource/Feline_calicivirus').
row('http://dbpedia.org/resource/Feline_coronavirus').
row('http://dbpedia.org/resource/Feline_cystitis').
row('http://dbpedia.org/resource/Feline_hepatic_lipidosis').
row('http://dbpedia.org/resource/Feline_hyperaldosteronism').
row('http://dbpedia.org/resource/Feline_hyperesthesia_syndrome').
row('http://dbpedia.org/resource/Feline_immunodeficiency_virus').
row('http://dbpedia.org/resource/Feline_infectious_anemia').
row('http://dbpedia.org/resource/Feline_infectious_peritonitis').
row('http://dbpedia.org/resource/Feline_leukemia_virus').
row('http://dbpedia.org/resource/Feline_lower_urinary_tract_disease').
row('http://dbpedia.org/resource/Feline_odontoclastic_resorptive_lesion').
row('http://dbpedia.org/resource/Feline_panleukopenia').
row('http://dbpedia.org/resource/Feline_spongiform_encephalopathy').
row('http://dbpedia.org/resource/Feline_viral_rhinotracheitis').
row('http://dbpedia.org/resource/Fibrosarcoma').
row('http://dbpedia.org/resource/Filariasis').
row('http://dbpedia.org/resource/Filicollosis').
row('http://dbpedia.org/resource/Filoviridae').
row('http://dbpedia.org/resource/Fin_rot').
row('http://dbpedia.org/resource/Fish_acute_toxicity_syndrome').
row('http://dbpedia.org/resource/Fish_diseases_and_parasites').
row('http://dbpedia.org/resource/Fish_dropsy').
row('http://dbpedia.org/resource/Fishkeeping').
row('http://dbpedia.org/resource/Fishpathogens.eu').
row('http://dbpedia.org/resource/Flacherie').
row('http://dbpedia.org/resource/Flat-chested_kitten_syndrome').
row('http://dbpedia.org/resource/Flavobacterium').
row('http://dbpedia.org/resource/Flea_allergy_dermatitis').
row('http://dbpedia.org/resource/Floppy_trunk_syndrome').
row('http://dbpedia.org/resource/Florida_keratopathy').
row('http://dbpedia.org/resource/Fluvir').
row('http://dbpedia.org/resource/Fog_fever').
row('http://dbpedia.org/resource/Foot-and-mouth_disease').
row('http://dbpedia.org/resource/Foot_rot').
row('http://dbpedia.org/resource/Fowl_cholera').
row('http://dbpedia.org/resource/Fowlpox').
row('http://dbpedia.org/resource/Fusarium').
row('http://dbpedia.org/resource/Gaffkaemia').
row('http://dbpedia.org/resource/Gallid_herpesvirus_1').
row('http://dbpedia.org/resource/Gapeworm').
row('http://dbpedia.org/resource/Gastric_dilatation_volvulus').
row('http://dbpedia.org/resource/Giardiasis').
row('http://dbpedia.org/resource/Gingival_enlargement').
row('http://dbpedia.org/resource/Giovannolaia').
row('http://dbpedia.org/resource/Glanders').
row('http://dbpedia.org/resource/Global_spread_of_H5N1').
row('http://dbpedia.org/resource/Glycogen-branching_enzyme_deficiency').
row('http://dbpedia.org/resource/Gnathostomiasis').
row('http://dbpedia.org/resource/Gongylonema_pulchrum').
row('http://dbpedia.org/resource/Gou_virus').
row('http://dbpedia.org/resource/Granulomatous_meningoencephalitis').
row('http://dbpedia.org/resource/Grass_sickness').
row('http://dbpedia.org/resource/Grass_tetany').
row('http://dbpedia.org/resource/HCoV-EMC/2012').
row('http://dbpedia.org/resource/Haemamoeba').
row('http://dbpedia.org/resource/Haemonchus_contortus').
row('http://dbpedia.org/resource/Haemoproteus').
row('http://dbpedia.org/resource/Haemoproteus_columbae').
row('http://dbpedia.org/resource/Haemoproteus_plataleae').
row('http://dbpedia.org/resource/Hairball').
row('http://dbpedia.org/resource/Halofolliculina_corallasia').
row('http://dbpedia.org/resource/Hardware_disease').
row('http://dbpedia.org/resource/Head_and_lateral_line_erosion').
row('http://dbpedia.org/resource/Headshaking').
row('http://dbpedia.org/resource/Heart_valve_dysplasia').
row('http://dbpedia.org/resource/Hemangiosarcoma').
row('http://dbpedia.org/resource/Hematodinium_perezi').
row('http://dbpedia.org/resource/Hemioniscus_balani').
row('http://dbpedia.org/resource/Hemorrhagic_gastroenteritis').
row('http://dbpedia.org/resource/Hemorrhagic_septicemia').
row('http://dbpedia.org/resource/Henipavirus').
row('http://dbpedia.org/resource/Henneguya_zschokkei').
row('http://dbpedia.org/resource/Hepatic_microvascular_dysplasia').
row('http://dbpedia.org/resource/Hereditary_equine_regional_dermal_asthenia').
row('http://dbpedia.org/resource/Highlands_J_virus').
row('http://dbpedia.org/resource/Hip_dysplasia_(canine)').
row('http://dbpedia.org/resource/Hippoboscidae').
row('http://dbpedia.org/resource/Histiocytoma_(dog)').
row('http://dbpedia.org/resource/Histomonas_meleagridis').
row('http://dbpedia.org/resource/Histomoniasis').
row('http://dbpedia.org/resource/Histoplasmosis').
row('http://dbpedia.org/resource/Hock_burns').
row('http://dbpedia.org/resource/Hookworm').
row('http://dbpedia.org/resource/Hoose_(disease)').
row('http://dbpedia.org/resource/Horse_colic').
row('http://dbpedia.org/resource/Hot_spot_(veterinary_medicine)').
row('http://dbpedia.org/resource/Huffia').
row('http://dbpedia.org/resource/Hygroma_(canine_disease)').
row('http://dbpedia.org/resource/Hyperesthesia').
row('http://dbpedia.org/resource/Hyperkalemic_periodic_paralysis').
row('http://dbpedia.org/resource/Hyperthyroidism').
row('http://dbpedia.org/resource/Hypertrophic_cardiomyopathy').
row('http://dbpedia.org/resource/Hypertrophic_osteodystrophy').
row('http://dbpedia.org/resource/Hypertrophic_osteopathy').
row('http://dbpedia.org/resource/Hypoadrenocorticism_in_dogs').
row('http://dbpedia.org/resource/Hypoplasia_of_dens').
row('http://dbpedia.org/resource/Icosta').
row('http://dbpedia.org/resource/Immune_mediated_polygenic_arthritis').
row('http://dbpedia.org/resource/Impaction_(animals)').
row('http://dbpedia.org/resource/Imperforate_lacrimal_punctum').
row('http://dbpedia.org/resource/Imposex').
row('http://dbpedia.org/resource/Infectious_bovine_keratoconjunctivitis').
row('http://dbpedia.org/resource/Infectious_bursal_disease').
row('http://dbpedia.org/resource/Infectious_canine_hepatitis').
row('http://dbpedia.org/resource/Infectious_hematopoietic_necrosis_virus').
row('http://dbpedia.org/resource/Infectious_hypodermal_and_hematopoietic_necrosis').
row('http://dbpedia.org/resource/Infectious_necrotic_hepatitis').
row('http://dbpedia.org/resource/Infectious_pancreatic_necrosis').
row('http://dbpedia.org/resource/Infectious_salmon_anemia_virus').
row('http://dbpedia.org/resource/Influenza').
row('http://dbpedia.org/resource/Influenza_A_virus').
row('http://dbpedia.org/resource/Influenza_A_virus_subtype_H5N1').
row('http://dbpedia.org/resource/Influenza_A_virus_subtype_H6N1').
row('http://dbpedia.org/resource/Interdigital_dermatitis_in_cattle').
row('http://dbpedia.org/resource/Intestinal_cancer_in_cats_and_dogs').
row('http://dbpedia.org/resource/Iris_cyst').
row('http://dbpedia.org/resource/Jaagsiekte').
row('http://dbpedia.org/resource/Jaagsiekte_sheep_retrovirus').
row('http://dbpedia.org/resource/Japanese_encephalitis').
row('http://dbpedia.org/resource/Jembrana_disease').
row('http://dbpedia.org/resource/Junctional_epidermolysis_bullosa_(veterinary_medicine)').
row('http://dbpedia.org/resource/Juvenile_cellulitis').
row('http://dbpedia.org/resource/Kennel_cough').
row('http://dbpedia.org/resource/Keratoconjunctivitis_sicca').
row('http://dbpedia.org/resource/Koi_herpes_virus').
row('http://dbpedia.org/resource/Kudoa_thyrsites').
row('http://dbpedia.org/resource/Kunjin_virus').
row('http://dbpedia.org/resource/Lagenidiosis').
row('http://dbpedia.org/resource/Lagos_bat_virus').
row('http://dbpedia.org/resource/Lameness_(equine)').
row('http://dbpedia.org/resource/Laminitis').
row('http://dbpedia.org/resource/Laryngeal_paralysis').
row('http://dbpedia.org/resource/Lassa_fever').
row('http://dbpedia.org/resource/Lassa_virus').
row('http://dbpedia.org/resource/Lavender_Foal_Syndrome').
row('http://dbpedia.org/resource/Legg%E2%80%93Calv%C3%A9%E2%80%93Perthes_syndrome').
row('http://dbpedia.org/resource/Leishmaniasis').
row('http://dbpedia.org/resource/Lens_luxation').
row('http://dbpedia.org/resource/Leptospirosis').
row('http://dbpedia.org/resource/Lethal_white_syndrome').
row('http://dbpedia.org/resource/Leucocytozoon').
row('http://dbpedia.org/resource/Leucocytozoon_andrewsi').
row('http://dbpedia.org/resource/Leucocytozoon_caprimulgi').
row('http://dbpedia.org/resource/Lick_granuloma').
row('http://dbpedia.org/resource/Limber_tail_syndrome').
row('http://dbpedia.org/resource/List_of_aquarium_diseases').
row('http://dbpedia.org/resource/List_of_diseases_of_the_honey_bee').
row('http://dbpedia.org/resource/List_of_dog_diseases').
row('http://dbpedia.org/resource/List_of_infectious_sheep_and_goat_diseases').
row('http://dbpedia.org/resource/Listeriosis_in_animals').
row('http://dbpedia.org/resource/Liver_cancer_in_cats_and_dogs').
row('http://dbpedia.org/resource/Ljungan_virus').
row('http://dbpedia.org/resource/Lloviu_cuevavirus').
row('http://dbpedia.org/resource/Lloviu_virus').
row('http://dbpedia.org/resource/Loa_loa_filariasis').
row('http://dbpedia.org/resource/London1_novel_CoV/2012').
row('http://dbpedia.org/resource/Louping_ill').
row('http://dbpedia.org/resource/Lujo_virus').
row('http://dbpedia.org/resource/Lumpy_skin_disease').
row('http://dbpedia.org/resource/Luxating_patella').
row('http://dbpedia.org/resource/Lymantria_dispar_multicapsid_nuclear_polyhedrosis_virus').
row('http://dbpedia.org/resource/Lymphangiectasia').
row('http://dbpedia.org/resource/Lymphocystis').
row('http://dbpedia.org/resource/Lymphocystivirus').
row('http://dbpedia.org/resource/Lymphocytic_choriomeningitis').
row('http://dbpedia.org/resource/Lymphoid_Leucosis').
row('http://dbpedia.org/resource/Lymphoma_in_animals').
row('http://dbpedia.org/resource/M74_syndrome').
row('http://dbpedia.org/resource/Malignant_edema').
row('http://dbpedia.org/resource/Malignant_histiocytosis').
row('http://dbpedia.org/resource/Mallein_test').
row('http://dbpedia.org/resource/Mammary_tumor').
row('http://dbpedia.org/resource/Mammomonogamus').
row('http://dbpedia.org/resource/Mange').
row('http://dbpedia.org/resource/Marburg_marburgvirus').
row('http://dbpedia.org/resource/Marburg_virus').
row('http://dbpedia.org/resource/Marburg_virus_disease').
row('http://dbpedia.org/resource/Marburgvirus').
row('http://dbpedia.org/resource/Mare_reproductive_loss_syndrome').
row('http://dbpedia.org/resource/Marek\'s_disease').
row('http://dbpedia.org/resource/Maripa_virus').
row('http://dbpedia.org/resource/Masticatory_muscle_myositis').
row('http://dbpedia.org/resource/Mastitis_in_dairy_cattle').
row('http://dbpedia.org/resource/Mastocytoma').
row('http://dbpedia.org/resource/Med-Vet-Net').
row('http://dbpedia.org/resource/Megaesophagus').
row('http://dbpedia.org/resource/Megalocytivirus').
row('http://dbpedia.org/resource/Melaka_virus').
row('http://dbpedia.org/resource/Melioidosis').
row('http://dbpedia.org/resource/Menoponidae').
row('http://dbpedia.org/resource/Mesalges_hirsutus').
row('http://dbpedia.org/resource/Mesnilium').
row('http://dbpedia.org/resource/Metastrongylosis').
row('http://dbpedia.org/resource/Metastrongylus').
row('http://dbpedia.org/resource/Metritis').
row('http://dbpedia.org/resource/Microlynchia').
row('http://dbpedia.org/resource/Middle_East_respiratory_syndrome').
row('http://dbpedia.org/resource/Middle_East_respiratory_syndrome_coronavirus').
row('http://dbpedia.org/resource/Miliary_dermatitis').
row('http://dbpedia.org/resource/Milk_fever').
row('http://dbpedia.org/resource/Mink_enteritis_virus').
row('http://dbpedia.org/resource/Mitral_valve_dysplasia').
row('http://dbpedia.org/resource/Mononegavirales').
row('http://dbpedia.org/resource/Moorhen_flea').
row('http://dbpedia.org/resource/Moose_sickness').
row('http://dbpedia.org/resource/Moraxella_bovis').
row('http://dbpedia.org/resource/Moredun_Research_Institute').
row('http://dbpedia.org/resource/Mouse_hepatitis_virus').
row('http://dbpedia.org/resource/Mouse_mammary_tumor_virus').
row('http://dbpedia.org/resource/Mouyassue_virus').
row('http://dbpedia.org/resource/Mud_fever').
row('http://dbpedia.org/resource/Muleshoe_virus').
row('http://dbpedia.org/resource/Multilobular_tumour_of_bone').
row('http://dbpedia.org/resource/Murine_leukemia_virus').
row('http://dbpedia.org/resource/Murrain').
row('http://dbpedia.org/resource/Mycobacterium_bovis').
row('http://dbpedia.org/resource/Mycobacterium_lepraemurium').
row('http://dbpedia.org/resource/Mycoplasma_hyopneumoniae').
row('http://dbpedia.org/resource/Mycoplasma_hyorhinis').
row('http://dbpedia.org/resource/Mycoplasma_meleagridis').
row('http://dbpedia.org/resource/Mycoplasma_synoviae').
row('http://dbpedia.org/resource/Myiasis').
row('http://dbpedia.org/resource/Myophthiria').
row('http://dbpedia.org/resource/Myopia_in_animals').
row('http://dbpedia.org/resource/Myxomatosis').
row('http://dbpedia.org/resource/Nanophyetus_salmincola').
row('http://dbpedia.org/resource/Necrotising_hepatopancreatitis').
row('http://dbpedia.org/resource/Necrotizing_meningoencephalitis').
row('http://dbpedia.org/resource/Neonatal_isoerythrolysis').
row('http://dbpedia.org/resource/Neospora_caninum').
row('http://dbpedia.org/resource/Newcastle_disease').
row('http://dbpedia.org/resource/Nicothoe_astaci').
row('http://dbpedia.org/resource/Nicothoe_tumulosa').
row('http://dbpedia.org/resource/Nose_cancer_in_cats_and_dogs').
row('http://dbpedia.org/resource/Nova_virus').
row('http://dbpedia.org/resource/Novel_virus').
row('http://dbpedia.org/resource/Novirhabdovirus').
row('http://dbpedia.org/resource/Novyella').
row('http://dbpedia.org/resource/Nuclear_sclerosis').
row('http://dbpedia.org/resource/Nutritional_muscular_dystrophy').
row('http://dbpedia.org/resource/Ocular_melanosis').
row('http://dbpedia.org/resource/Oesophagostomum').
row('http://dbpedia.org/resource/Oil_Toxicity').
row('http://dbpedia.org/resource/Olfersia').
row('http://dbpedia.org/resource/Opisthorchis_felineus').
row('http://dbpedia.org/resource/Orf_(disease)').
row('http://dbpedia.org/resource/Ornidazole').
row('http://dbpedia.org/resource/Ornithobacterium_rhinotracheale').
row('http://dbpedia.org/resource/Ornithoctona').
row('http://dbpedia.org/resource/Ornithoica').
row('http://dbpedia.org/resource/Ornithomya').
row('http://dbpedia.org/resource/Ornithomya_cecropis').
row('http://dbpedia.org/resource/Ornithophila').
row('http://dbpedia.org/resource/Oropouche_fever').
row('http://dbpedia.org/resource/Orphan_virus').
row('http://dbpedia.org/resource/Osteochondritis_dissecans').
row('http://dbpedia.org/resource/Osteosarcoma').
row('http://dbpedia.org/resource/Otitis_externa_in_animals').
row('http://dbpedia.org/resource/Ovine_rinderpest').
row('http://dbpedia.org/resource/Oxbow_virus').
row('http://dbpedia.org/resource/P%C3%A9brine').
row('http://dbpedia.org/resource/PEPPADEP').
row('http://dbpedia.org/resource/Pacheco\'s_disease').
row('http://dbpedia.org/resource/Pachyostosis').
row('http://dbpedia.org/resource/Paecilomyces_fumosoroseus').
row('http://dbpedia.org/resource/Panosteitis').
row('http://dbpedia.org/resource/Panzootic').
row('http://dbpedia.org/resource/Papernaia').
row('http://dbpedia.org/resource/Paracapillaria_xenentodoni').
row('http://dbpedia.org/resource/Paragonimiasis').
row('http://dbpedia.org/resource/Paratuberculosis').
row('http://dbpedia.org/resource/Pasteurella_anatis').
row('http://dbpedia.org/resource/Pasteurella_canis').
row('http://dbpedia.org/resource/Pasteurella_dagmatis').
row('http://dbpedia.org/resource/Pasteurella_langaa').
row('http://dbpedia.org/resource/Pasteurella_multocida').
row('http://dbpedia.org/resource/Pasteurella_stomatis').
row('http://dbpedia.org/resource/Pasteurellosis').
row('http://dbpedia.org/resource/Pathogenic_Escherichia_coli').
row('http://dbpedia.org/resource/Perianal_gland_tumor').
row('http://dbpedia.org/resource/Perineal_hernia').
row('http://dbpedia.org/resource/Persistent_pupillary_membrane').
row('http://dbpedia.org/resource/Pfiesteria_piscicida').
row('http://dbpedia.org/resource/Philophthalmus_gralli').
row('http://dbpedia.org/resource/Philornis').
row('http://dbpedia.org/resource/Philornis_downsi').
row('http://dbpedia.org/resource/Phocine_distemper_virus').
row('http://dbpedia.org/resource/Photobacterium_damselae_subsp._piscicida').
row('http://dbpedia.org/resource/Photosensitivity_in_animals').
row('http://dbpedia.org/resource/Phthona').
row('http://dbpedia.org/resource/Pigeon_fever').
row('http://dbpedia.org/resource/Pigeon_pox').
row('http://dbpedia.org/resource/Plague_(disease)').
row('http://dbpedia.org/resource/Plasmodium_accipiteris').
row('http://dbpedia.org/resource/Plasmodium_anasum').
row('http://dbpedia.org/resource/Plasmodium_ashfordi').
row('http://dbpedia.org/resource/Plasmodium_bambusicolai').
row('http://dbpedia.org/resource/Plasmodium_bertii').
row('http://dbpedia.org/resource/Plasmodium_buteonis').
row('http://dbpedia.org/resource/Plasmodium_circumflexum').
row('http://dbpedia.org/resource/Plasmodium_coggeshalli').
row('http://dbpedia.org/resource/Plasmodium_corradettii').
row('http://dbpedia.org/resource/Plasmodium_dissanaikei').
row('http://dbpedia.org/resource/Plasmodium_durae').
row('http://dbpedia.org/resource/Plasmodium_fallax').
row('http://dbpedia.org/resource/Plasmodium_gabaldoni').
row('http://dbpedia.org/resource/Plasmodium_gallinaceum').
row('http://dbpedia.org/resource/Plasmodium_garnhami').
row('http://dbpedia.org/resource/Plasmodium_globularis').
row('http://dbpedia.org/resource/Plasmodium_gundersi').
row('http://dbpedia.org/resource/Plasmodium_hegneri').
row('http://dbpedia.org/resource/Plasmodium_hermani').
row('http://dbpedia.org/resource/Plasmodium_jiangi').
row('http://dbpedia.org/resource/Plasmodium_juxtanucleare').
row('http://dbpedia.org/resource/Plasmodium_lucens').
row('http://dbpedia.org/resource/Plasmodium_lutzi').
row('http://dbpedia.org/resource/Plasmodium_megaglobularis').
row('http://dbpedia.org/resource/Plasmodium_multivacuolaris').
row('http://dbpedia.org/resource/Plasmodium_octamerium').
row('http://dbpedia.org/resource/Plasmodium_paddae').
row('http://dbpedia.org/resource/Plasmodium_papernai').
row('http://dbpedia.org/resource/Plasmodium_parahexamerium').
row('http://dbpedia.org/resource/Plasmodium_paranucleophilum').
row('http://dbpedia.org/resource/Plasmodium_pinotti').
row('http://dbpedia.org/resource/Plasmodium_polare').
row('http://dbpedia.org/resource/Plasmodium_tejerai').
row('http://dbpedia.org/resource/Plasmodium_tenue').
row('http://dbpedia.org/resource/Plasmodium_unalis').
row('http://dbpedia.org/resource/Plasmodium_vaughani').
row('http://dbpedia.org/resource/Pneumonia_(non-human)').
row('http://dbpedia.org/resource/Pneumonic_plague').
row('http://dbpedia.org/resource/Polioencephalomalacia').
row('http://dbpedia.org/resource/Poll_evil').
row('http://dbpedia.org/resource/Polydipsia_in_birds').
row('http://dbpedia.org/resource/Polyneuropathy_in_dogs_and_cats').
row('http://dbpedia.org/resource/Porcine_Circovirus_Associated_Disease').
row('http://dbpedia.org/resource/Porcine_enzootic_pneumonia').
row('http://dbpedia.org/resource/Porcine_epidemic_diarrhea_virus').
row('http://dbpedia.org/resource/Porcine_epidemic_diarrhoea').
row('http://dbpedia.org/resource/Porcine_intestinal_spirochaetosis').
row('http://dbpedia.org/resource/Porcine_parvovirus').
row('http://dbpedia.org/resource/Porcine_reproductive_and_respiratory_syndrome_virus').
row('http://dbpedia.org/resource/Porcine_stress_syndrome').
row('http://dbpedia.org/resource/Portosystemic_shunt').
row('http://dbpedia.org/resource/Potomac_Horse_Fever').
row('http://dbpedia.org/resource/Poultry_disease').
row('http://dbpedia.org/resource/Progressive_retinal_atrophy').
row('http://dbpedia.org/resource/Protothecosis').
row('http://dbpedia.org/resource/Proventricular_Dilatation_Disease').
row('http://dbpedia.org/resource/Pseudocowpox').
row('http://dbpedia.org/resource/Pseudolynchia').
row('http://dbpedia.org/resource/Pseudolynchia_canariensis').
row('http://dbpedia.org/resource/Pseudorabies').
row('http://dbpedia.org/resource/Psittacine_beak_and_feather_disease').
row('http://dbpedia.org/resource/Psittacosis').
row('http://dbpedia.org/resource/Pug_Dog_encephalitis').
row('http://dbpedia.org/resource/Puppy_strangles').
row('http://dbpedia.org/resource/Purpura_haemorrhagica').
row('http://dbpedia.org/resource/Puumala_virus').
row('http://dbpedia.org/resource/Pyometra').
row('http://dbpedia.org/resource/Pythiosis').
row('http://dbpedia.org/resource/Q_fever').
row('http://dbpedia.org/resource/Quarantine_tank').
row('http://dbpedia.org/resource/Quittor').
row('http://dbpedia.org/resource/Quokkapox_virus').
row('http://dbpedia.org/resource/Rabbit_haemorrhagic_disease').
row('http://dbpedia.org/resource/Rabbitpox').
row('http://dbpedia.org/resource/Rabies').
row('http://dbpedia.org/resource/Racehorse_injuries').
row('http://dbpedia.org/resource/Raillietina').
row('http://dbpedia.org/resource/Raillietina_echinobothrida').
row('http://dbpedia.org/resource/Rainscald').
row('http://dbpedia.org/resource/Ranavirus').
row('http://dbpedia.org/resource/Rangeliosis').
row('http://dbpedia.org/resource/Rat-bite_fever').
row('http://dbpedia.org/resource/Ravn_virus').
row('http://dbpedia.org/resource/Recurrent_airway_obstruction').
row('http://dbpedia.org/resource/Relapsing_fever').
row('http://dbpedia.org/resource/Renibacterium_salmoninarum').
row('http://dbpedia.org/resource/Reston_virus').
row('http://dbpedia.org/resource/Retinal_dysplasia').
row('http://dbpedia.org/resource/Rickettsia_felis').
row('http://dbpedia.org/resource/Rickettsia_heilongjiangensis').
row('http://dbpedia.org/resource/Rickettsia_helvetica').
row('http://dbpedia.org/resource/Rickettsia_peacockii').
row('http://dbpedia.org/resource/Rickettsia_prowazekii').
row('http://dbpedia.org/resource/Rickettsia_rickettsii').
row('http://dbpedia.org/resource/Riemerella_anatipestifer').
row('http://dbpedia.org/resource/Rift_Valley_fever').
row('http://dbpedia.org/resource/Rimantadine').
row('http://dbpedia.org/resource/Rinderpest').
row('http://dbpedia.org/resource/Ringtail_(disease)').
row('http://dbpedia.org/resource/Rio_Mamore_virus').
row('http://dbpedia.org/resource/Rio_Segundo_virus').
row('http://dbpedia.org/resource/Risk_assessment_for_organic_swine_health').
row('http://dbpedia.org/resource/Risk_of_Missed_PRRS_PCR_Detection').
row('http://dbpedia.org/resource/Rockport_virus').
row('http://dbpedia.org/resource/Rocky_Mountain_spotted_fever').
row('http://dbpedia.org/resource/Runting-stunting_syndrome_in_broilers').
row('http://dbpedia.org/resource/SCID_in_dogs').
row('http://dbpedia.org/resource/SFTS_virus').
row('http://dbpedia.org/resource/SL-CoV-WIV1').
row('http://dbpedia.org/resource/SMEDI').
row('http://dbpedia.org/resource/Sacculina').
row('http://dbpedia.org/resource/Saemundssonia').
row('http://dbpedia.org/resource/Salmon_louse').
row('http://dbpedia.org/resource/Salmon_poisoning_disease').
row('http://dbpedia.org/resource/Salmonellosis').
row('http://dbpedia.org/resource/Samoyed_hereditary_glomerulopathy').
row('http://dbpedia.org/resource/Saprolegnia').
row('http://dbpedia.org/resource/Savaging').
row('http://dbpedia.org/resource/Scaly_foot').
row('http://dbpedia.org/resource/Scaly_leg').
row('http://dbpedia.org/resource/Schistocephalus').
row('http://dbpedia.org/resource/Schistocephalus_solidus').
row('http://dbpedia.org/resource/Schistosoma_nasale').
row('http://dbpedia.org/resource/Schistosoma_spindale').
row('http://dbpedia.org/resource/Schistosomiasis').
row('http://dbpedia.org/resource/Schmallenberg_virus').
row('http://dbpedia.org/resource/Scotty_Cramp').
row('http://dbpedia.org/resource/Scrapie').
row('http://dbpedia.org/resource/Scrub_typhus').
row('http://dbpedia.org/resource/Scurvy').
row('http://dbpedia.org/resource/Sebaceous_adenitis').
row('http://dbpedia.org/resource/Sendai_virus').
row('http://dbpedia.org/resource/Septicemic_plague').
row('http://dbpedia.org/resource/Serang_virus').
row('http://dbpedia.org/resource/Severe_acute_respiratory_syndrome').
row('http://dbpedia.org/resource/Severe_combined_immunodeficiency_(non-human)').
row('http://dbpedia.org/resource/Severe_fever_with_thrombocytopenia_syndrome').
row('http://dbpedia.org/resource/Shar_Pei_fever').
row('http://dbpedia.org/resource/Sheeppox').
row('http://dbpedia.org/resource/Shimoni_bat_virus').
row('http://dbpedia.org/resource/Shope_papilloma_virus').
row('http://dbpedia.org/resource/Simian_immunodeficiency_virus').
row('http://dbpedia.org/resource/Skeletal_eroding_band').
row('http://dbpedia.org/resource/Skin_cancer_in_cats_and_dogs').
row('http://dbpedia.org/resource/Skin_cancer_in_horses').
row('http://dbpedia.org/resource/Snakehead_rhabdovirus').
row('http://dbpedia.org/resource/Sodoku').
row('http://dbpedia.org/resource/Soft_tissue_sarcoma_in_cats_and_dogs').
row('http://dbpedia.org/resource/Sphaerothecum_destruens').
row('http://dbpedia.org/resource/Spider_lamb_syndrome').
row('http://dbpedia.org/resource/Spillover_infection').
row('http://dbpedia.org/resource/Spirometra_erinaceieuropaei').
row('http://dbpedia.org/resource/Spironucleus_salmonicida').
row('http://dbpedia.org/resource/Spring_viraemia_of_carp').
row('http://dbpedia.org/resource/Starfish_wasting_disease').
row('http://dbpedia.org/resource/Stenotic_nares').
row('http://dbpedia.org/resource/Stichocotyle').
row('http://dbpedia.org/resource/Sticky_mouse').
row('http://dbpedia.org/resource/Stilbometopa').
row('http://dbpedia.org/resource/Stockpiling_antiviral_medications_for_pandemic_influenza').
row('http://dbpedia.org/resource/Strangles').
row('http://dbpedia.org/resource/Streptococcal_infection_in_poultry').
row('http://dbpedia.org/resource/Streptococcus_iniae').
row('http://dbpedia.org/resource/Streptothricosis').
row('http://dbpedia.org/resource/Strigiphilus_garylarsoni').
row('http://dbpedia.org/resource/Struthibosca').
row('http://dbpedia.org/resource/Subvalvular_aortic_stenosis_(non-human)').
row('http://dbpedia.org/resource/Sudan_ebolavirus').
row('http://dbpedia.org/resource/Sudan_virus').
row('http://dbpedia.org/resource/Sudden_acquired_retinal_degeneration').
row('http://dbpedia.org/resource/Surra').
row('http://dbpedia.org/resource/Sweating_sickness_(cattle)').
row('http://dbpedia.org/resource/Sweet_itch').
row('http://dbpedia.org/resource/Swim_bladder_disease').
row('http://dbpedia.org/resource/Swimmer\'s_itch').
row('http://dbpedia.org/resource/Swine_brucellosis').
row('http://dbpedia.org/resource/Swine_vesicular_disease').
row('http://dbpedia.org/resource/Swinepox').
row('http://dbpedia.org/resource/Sylvatic').
row('http://dbpedia.org/resource/Symbion').
row('http://dbpedia.org/resource/Synchysis_scintillans').
row('http://dbpedia.org/resource/Syngamus_merulae').
row('http://dbpedia.org/resource/Ta%C3%AF_Forest_ebolavirus').
row('http://dbpedia.org/resource/Ta%C3%AF_Forest_virus').
row('http://dbpedia.org/resource/Taura_syndrome').
row('http://dbpedia.org/resource/Tenacibaculum_soleae').
row('http://dbpedia.org/resource/Tetracapsuloides_bryosalmonae').
row('http://dbpedia.org/resource/Thailand_virus').
row('http://dbpedia.org/resource/Thelaziasis').
row('http://dbpedia.org/resource/Thiamine').
row('http://dbpedia.org/resource/Thompsonia_(barnacle)').
row('http://dbpedia.org/resource/Tibial_dyschondroplasia').
row('http://dbpedia.org/resource/Torovirinae').
row('http://dbpedia.org/resource/Torticollis').
row('http://dbpedia.org/resource/Toxascaris_leonina').
row('http://dbpedia.org/resource/Toxocariasis').
row('http://dbpedia.org/resource/Toxoplasma_gondii').
row('http://dbpedia.org/resource/Toxoplasmosis').
row('http://dbpedia.org/resource/Tracheal_collapse').
row('http://dbpedia.org/resource/Transmissible_mink_encephalopathy').
row('http://dbpedia.org/resource/Trichiasis').
row('http://dbpedia.org/resource/Trichobilharzia_regenti').
row('http://dbpedia.org/resource/Trichomonas_gallinae').
row('http://dbpedia.org/resource/Tricuspid_valve_dysplasia').
row('http://dbpedia.org/resource/Tropical_theileriosis').
row('http://dbpedia.org/resource/Trypanosoma').
row('http://dbpedia.org/resource/Tularemia').
row('http://dbpedia.org/resource/Turkey_coronavirus').
row('http://dbpedia.org/resource/Turkey_viral_hepatitis').
row('http://dbpedia.org/resource/Turkeypox').
row('http://dbpedia.org/resource/Tyzzer\'s_disease').
row('http://dbpedia.org/resource/Ulcerative_dermal_necrosis').
row('http://dbpedia.org/resource/Ulcerative_dermatitis').
row('http://dbpedia.org/resource/Vaccine-associated_sarcoma').
row('http://dbpedia.org/resource/Variola_caprina').
row('http://dbpedia.org/resource/Velvet_(fish_disease)').
row('http://dbpedia.org/resource/Venezuelan_equine_encephalitis_virus').
row('http://dbpedia.org/resource/Verminous_haemorrhagic_dermatitis_(cattle)').
row('http://dbpedia.org/resource/Veterinary_virology').
row('http://dbpedia.org/resource/Vibrio_anguillarum').
row('http://dbpedia.org/resource/Vietnamese_tuberculosis').
row('http://dbpedia.org/resource/Viral_arthritis_(poultry)').
row('http://dbpedia.org/resource/Viral_hemorrhagic_septicemia').
row('http://dbpedia.org/resource/Visceral_gout').
row('http://dbpedia.org/resource/Visna_virus').
row('http://dbpedia.org/resource/Vitamin_D_and_respiratory_tract_infections').
row('http://dbpedia.org/resource/Vogt%E2%80%93Koyanagi%E2%80%93Harada_syndrome').
row('http://dbpedia.org/resource/Walleye_epidermal_hyperplasia_virus').
row('http://dbpedia.org/resource/Well-bird_exam').
row('http://dbpedia.org/resource/West_Nile_virus').
row('http://dbpedia.org/resource/Western_equine_encephalitis_virus').
row('http://dbpedia.org/resource/Wet-tail').
row('http://dbpedia.org/resource/White_Bream_virus').
row('http://dbpedia.org/resource/White_band_disease').
row('http://dbpedia.org/resource/White_dog_shaker_syndrome').
row('http://dbpedia.org/resource/White_nose_syndrome').
row('http://dbpedia.org/resource/White_pox_disease').
row('http://dbpedia.org/resource/White_spot_syndrome').
row('http://dbpedia.org/resource/Whitetail_Deer_Cutaneous_Fibroma').
row('http://dbpedia.org/resource/Wildlife_disease').
row('http://dbpedia.org/resource/Withering_abalone_syndrome').
row('http://dbpedia.org/resource/Wobbler_disease').
row('http://dbpedia.org/resource/Wobbly_hedgehog_syndrome').
row('http://dbpedia.org/resource/Wry_nose').
row('http://dbpedia.org/resource/Xuan_Son_virus').
row('http://dbpedia.org/resource/Yellow-band_disease').
row('http://dbpedia.org/resource/Yellowhead_disease').
row('http://dbpedia.org/resource/Zamia_staggers').
row('http://dbpedia.org/resource/Zoonosis').
row('http://dbpedia.org/resource/Zoophilia_and_health').
row('http://dbpedia.org/resource/Zygomycosis').
